name: Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TUMBLR_TOKEN: ${{ secrets.TUMBLR_TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
    - run: npm ci
    - run: npm test -- --coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
