name: Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  auth:
    runs-on: ubuntu-latest

    steps:
      - name: Get Tumblr access token
        id: auth
        uses: MarkSuckerberg/tumblr-auth-action@v1.0.0
        with:
          secrets-token: ${{ secrets.SECRETS_ACCESS_TOKEN }}
          tumblr-refresh-token: ${{ secrets.TUMBLR_REFRESH_TOKEN }}
          tumblr-client-id: ${{ secrets.TUMBLR_CLIENT_ID }}
          tumblr-client-secret: ${{ secrets.TUMBLR_CLIENT_SECRET }}
          token-name: TUMBLR_REFRESH_TOKEN
    outputs:
      tumblr-token: ${{ steps.auth.outputs.tumblr-token }}

  build:
    runs-on: ubuntu-latest
    needs: auth

    env:
      TUMBLR_TOKEN: ${{ needs.auth.outputs.tumblr-token }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm test -- --coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
